apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - serviceaccounts.yaml
  - backend.yaml
  - worker.yaml
  - frontend.yaml
  - backend-ingress.yaml
  - frontend-ingress.yaml
  - hpa.yaml
