apiVersion: v1
kind: Secret
metadata:
  name: docops-secrets
  namespace: docops
type: Opaque
stringData:
  DATABASE_URL: postgresql+psycopg://docops:replace-me@docops-rds.cluster-xxxxxxxx.us-east-1.rds.amazonaws.com:5432/docops
