apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: docops
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/docops-backend-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: docops
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/docops-worker-irsa
